[build-system]
requires = ["setuptools>=64", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "orcabridge"
description = "Function-based Oracapod Pipeline implementation in Python"
dynamic = ["version"]
dependencies = [
    "xxhash",
 "networkx",
 "typing_extensions",
 "matplotlib>=3.10.3",
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/walkerlab/orcabridge"

[project.optional-dependencies]
redis = ["redis>=6.2.0"]


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/orcabridge/_version.py"

[dependency-groups]
dev = [
    "httpie>=3.2.4",
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "redis>=6.2.0",
    "ruff>=0.11.11",
    "tqdm>=4.67.1",
]
